apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-capstone
  labels:
    app: capstone
spec:
  replicas: 3
  strategy:
    rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: fadykhallaf/capstone:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP