version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/capstone
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.1.0/hadolint-Linux-x86_64  
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: linting
          command: |
            . venv/bin/activate
            make 
      
  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: capstone docker image
          command: |
            docker build --tag=capstone .
            docker images ls
      - run:
          name: push to dockerhub
          command: |
            dockerpath="fadykhallaf/capstone:latest"
            docker tag capstone:latest $dockerpath
            echo "Docker ID and Image: $dockerpath"
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker image push $dockerpath

workflows:
    default:
        jobs:
          - lint